image:
  repository: ghcr.io/galpodlipnik1/rbf-api
  tag: "76a8bec"

imagePullSecrets:
  - ghcr-pull

service:
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: rbf-api.galpodlipnik.com
  proxyBodySize: 100m
